# Generated by Django 6.0.3 on 2026-03-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('os_info', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('is_up', models.BooleanField(default=True)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
                ('open_ports_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='目标 IP 或 域名 (支持网段 e.g. 192.168.1.0/24)', max_length=255)),
                ('scan_type', models.CharField(choices=[('quick', '快速扫描'), ('full', '全端口扫描'), ('service', '服务识别')], default='quick', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '进行中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True, help_text='简单的结果摘要', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('service_version', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('banner', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='scanner.asset')),
            ],
            options={
                'ordering': ['port_number'],
                'unique_together': {('asset', 'port_number', 'protocol')},
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', '低危'), ('MEDIUM', '中危'), ('HIGH', '高危'), ('CRITICAL', '严重')], default='LOW', max_length=20)),
                ('solution', models.TextField(blank=True)),
                ('cve_id', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='scanner.asset')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='scanner.port')),
            ],
        ),
    ]
