# Generated by Django 6.0.3 on 2026-03-13 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_category_tag_asset_business_system_asset_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DNS', 'DNS'), ('HTTP', 'HTTP'), ('TLS', 'TLS'), ('LOG', 'LOG')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=20, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('raw', models.TextField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=1)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passive_events', to='scanner.asset')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
