# Generated by Django 6.0.3 on 2026-03-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_passiveevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enable_tcp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='enable_udp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='host_discovery',
            field=models.CharField(choices=[('DEFAULT', '默认'), ('PING_ONLY', '仅主机发现 (-sn)'), ('ICMP', 'ICMP 探测 (-PE -PP)'), ('NO_PING', '跳过主机发现 (-Pn)')], default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='ports',
            field=models.CharField(blank=True, help_text='端口范围 (如 80,443,8000-9000)。留空按扫描类型默认。', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tcp_scan',
            field=models.CharField(choices=[('SYN', 'SYN 扫描 (-sS)'), ('CONNECT', 'TCP 连接扫描 (-sT)')], default='SYN', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='timing',
            field=models.IntegerField(default=4, help_text='Nmap timing 模板 (-T0..-T5)'),
        ),
    ]
