# Generated by Django 6.0.3 on 2026-03-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_task_enable_tcp_task_enable_udp_task_host_discovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='app_fingerprint',
            field=models.CharField(blank=True, help_text='应用指纹 (如 Nginx/1.18.0, Tomcat/9.0.31)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='is_vulnerable_version',
            field=models.BooleanField(default=False, help_text='是否为高风险/老旧版本'),
        ),
    ]
