# Generated by Django 6.0.3 on 2026-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_port_app_fingerprint_port_is_vulnerable_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='network_segment',
            field=models.CharField(blank=True, help_text='所属网段 (如 192.168.1.0/24)', max_length=50, null=True),
        ),
    ]
