# Generated by Django 6.0.3 on 2026-03-13 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_asset_network_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('NEW_ASSET', '陌生设备接入'), ('PORT_CHANGE', '非法端口开放'), ('VULNERABILITY', '高危漏洞/风险'), ('OFFLINE', '设备异常下线'), ('SERVICE_CHANGE', '服务变更'), ('PROBE', '恶意探测/黑产探针')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', '提示'), ('MEDIUM', '一般'), ('HIGH', '重要'), ('CRITICAL', '紧急')], default='LOW', max_length=20)),
                ('status', models.CharField(choices=[('UNREAD', '未读'), ('READ', '已读'), ('RESOLVED', '已处理'), ('IGNORED', '忽略')], default='UNREAD', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scanner.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
