# Generated by Django 6.0.3 on 2026-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='discovery_method',
            field=models.CharField(choices=[('ACTIVE', '主动扫描'), ('PASSIVE', '被动探测'), ('MANUAL', '手动录入')], default='ACTIVE', max_length=20),
        ),
    ]
