# Generated by Django 6.0.3 on 2026-03-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_asset_discovery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='script_categories',
            field=models.CharField(blank=True, default='vuln,auth,default', help_text='NSE 脚本类别，多个用逗号隔开 (如: vuln,auth,brute)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='use_scripts',
            field=models.BooleanField(default=False, verbose_name='启用 NSE 脚本'),
        ),
    ]
