# Generated by Django 6.0.3 on 2026-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_task_script_categories_task_use_scripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scan_type',
            field=models.CharField(choices=[('quick', '快速扫描'), ('normal', '标准扫描'), ('deep', '深度扫描'), ('service', '服务识别'), ('vuln', '漏洞扫描')], default='quick', max_length=20),
        ),
    ]
