# Generated by Django 6.0.3 on 2026-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_alter_task_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('NEW_ASSET', '陌生设备接入'), ('PORT_CHANGE', '非法端口开放'), ('VULNERABILITY', '高危漏洞/风险'), ('OFFLINE', '设备异常下线'), ('SERVICE_CHANGE', '服务变更'), ('PROBE', '恶意探测/黑产探针')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('LOW', '提示'), ('MEDIUM', '一般'), ('HIGH', '重要'), ('CRITICAL', '紧急')], db_index=True, default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('UNREAD', '未读'), ('READ', '已读'), ('RESOLVED', '已处理'), ('IGNORED', '忽略')], db_index=True, default='UNREAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='business_system',
            field=models.CharField(blank=True, db_index=True, help_text='归属业务系统', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.CharField(blank=True, db_index=True, help_text='归属部门', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='importance',
            field=models.IntegerField(choices=[(0, '普通'), (1, '重要'), (2, '关键核心')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_up',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_scanned',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='network_segment',
            field=models.CharField(blank=True, db_index=True, help_text='所属网段 (如 192.168.1.0/24)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_info',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '进行中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='target',
            field=models.CharField(db_index=True, help_text='目标 IP 或 域名 (支持网段 e.g. 192.168.1.0/24)', max_length=255),
        ),
    ]
