# Generated by Django 6.0.3 on 2026-03-16 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_alter_alert_alert_type_alter_alert_severity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名称')),
                ('channel', models.CharField(choices=[('EMAIL', '邮件通知'), ('DINGTALK', '钉钉'), ('WECHAT_WORK', '企业微信'), ('SLACK', 'Slack'), ('WEBHOOK', '自定义Webhook')], max_length=20, verbose_name='通知渠道')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('email_recipients', models.TextField(blank=True, help_text='多个邮箱用逗号分隔', verbose_name='邮件收件人')),
                ('webhook_url', models.CharField(blank=True, max_length=500, verbose_name='Webhook地址')),
                ('webhook_secret', models.CharField(blank=True, max_length=200, verbose_name='密钥')),
                ('notify_on_scan_complete', models.BooleanField(default=False, verbose_name='扫描完成通知')),
                ('notify_on_new_asset', models.BooleanField(default=False, verbose_name='发现新资产通知')),
                ('notify_on_asset_offline', models.BooleanField(default=False, verbose_name='资产离线通知')),
                ('notify_on_vulnerability', models.BooleanField(default=False, verbose_name='漏洞告警通知')),
                ('notify_on_alert', models.BooleanField(default=True, verbose_name='告警通知')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '通知配置',
                'verbose_name_plural': '通知配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='报告名称')),
                ('report_type', models.CharField(choices=[('ASSET', '资产报告'), ('SCAN', '扫描报告'), ('ALERT', '告警报告'), ('VULN', '漏洞报告')], max_length=20, verbose_name='报告类型')),
                ('file', models.FileField(upload_to='reports/', verbose_name='报告文件')),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=10, verbose_name='文件格式')),
                ('asset_count', models.IntegerField(default=0, verbose_name='资产数量')),
                ('alert_count', models.IntegerField(default=0, verbose_name='告警数量')),
                ('vuln_count', models.IntegerField(default=0, verbose_name='漏洞数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('scan_type', models.CharField(choices=[('quick', '快速扫描'), ('normal', '标准扫描'), ('deep', '深度扫描'), ('service', '服务识别'), ('vuln', '漏洞扫描')], default='quick', max_length=20, verbose_name='扫描类型')),
                ('ports', models.CharField(blank=True, max_length=100, null=True, verbose_name='端口范围')),
                ('enable_tcp', models.BooleanField(default=True, verbose_name='启用TCP扫描')),
                ('enable_udp', models.BooleanField(default=False, verbose_name='启用UDP扫描')),
                ('tcp_scan', models.CharField(choices=[('SYN', 'SYN 扫描'), ('CONNECT', 'TCP 连接扫描')], default='SYN', max_length=20, verbose_name='TCP扫描方式')),
                ('host_discovery', models.CharField(choices=[('DEFAULT', '默认'), ('PING_ONLY', '仅主机发现'), ('ICMP', 'ICMP探测'), ('NO_PING', '跳过主机发现')], default='DEFAULT', max_length=20, verbose_name='主机发现方式')),
                ('timing', models.IntegerField(default=4, verbose_name='扫描速度(T0-T5)')),
                ('use_scripts', models.BooleanField(default=False, verbose_name='启用NSE脚本')),
                ('script_categories', models.CharField(blank=True, max_length=100, null=True, verbose_name='脚本类别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '扫描模板',
                'verbose_name_plural': '扫描模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('password_correct', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败')], max_length=10, verbose_name='密码状态')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['-login_time'], name='scanner_log_login_t_f68d4c_idx'), models.Index(fields=['username', '-login_time'], name='scanner_log_usernam_0082ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20, verbose_name='通知渠道')),
                ('recipient', models.CharField(max_length=255, verbose_name='收件人')),
                ('subject', models.CharField(max_length=255, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.CharField(choices=[('PENDING', '等待发送'), ('SENT', '发送成功'), ('FAILED', '发送失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.notificationsettings', verbose_name='通知配置')),
            ],
            options={
                'verbose_name': '通知日志',
                'verbose_name_plural': '通知日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('target', models.CharField(max_length=255, verbose_name='目标')),
                ('frequency', models.CharField(choices=[('DAILY', '每天'), ('WEEKLY', '每周'), ('MONTHLY', '每月')], default='DAILY', max_length=20, verbose_name='执行频率')),
                ('cron_expression', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cron表达式')),
                ('day_of_week', models.IntegerField(blank=True, null=True, verbose_name='周几执行(0-6)')),
                ('hour', models.IntegerField(default=2, verbose_name='执行小时')),
                ('minute', models.IntegerField(default=0, verbose_name='执行分钟')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.scantemplate', verbose_name='扫描模板')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='操作用户')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('VIEW', '查看'), ('SCAN', '扫描'), ('EXPORT', '导出'), ('IMPORT', '导入'), ('LOGIN', '登录'), ('LOGOUT', '登出'), ('OTHER', '其他')], max_length=20, verbose_name='操作类型')),
                ('resource', models.CharField(max_length=100, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='资源ID')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作审计日志',
                'verbose_name_plural': '操作审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scanner_aud_created_1d0cf7_idx'), models.Index(fields=['user', '-created_at'], name='scanner_aud_user_id_398f68_idx'), models.Index(fields=['action', '-created_at'], name='scanner_aud_action_7ce757_idx')],
            },
        ),
    ]
